name: Release - Build and push image

on:
  workflow_run:
    workflows: ["Create release and tags"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Github Container Registry
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 #v3.2.0
      with:
        registry: ghcr.io
        username: mindriddler
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest tag
      id: latest_tag
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Build & Tag Docker Image
      run: |
        export DOCKER_BUILDKIT=1
        docker build --build-arg GITHUB_ACTION=true \
          --file ./Docker/Dockerfile \
          --tag ghcr.io/mindriddler/discord-bot:${{ env.LATEST_TAG }} \
          --tag ghcr.io/mindriddler/discord-bot:latest .
    - name: Push Docker Image
      run: |
        docker image push --all-tags ghcr.io/mindriddler/discord-bot

    - name: Delete all untagged images
      uses: actions/delete-package-versions@v5
      with:
        owner: ${{ github.repository_owner }}
        package-name: "discord-bot"
        package-type: "container"
        token: ${{ secrets.GITHUB_TOKEN }}
        min-versions-to-keep: 1
